apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubecf-default-psp
  namespace: default
rules:
- apiGroups:
  - policy
  resourceNames:
  - kubecf-default
  resources:
  - podsecuritypolicies
  verbs:
  - use
